language: node_js
node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/yarn
    - ~/.cache
    - .next/cache

env:
  global:
    - CC_TEST_REPORTER_ID=bd52cc3d15407e617ccdc96656dfcb8c8a6d9c4a47056490fd4c05952f1c33a3

jobs:
  include:
    before_script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

    script:
      - yarn format:check
      - yarn lint
      - yarn test --coverage
      - yarn test:integration:ci

    after_script:
      - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
