language: node_js
node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

jobs:
  include:
    script:
      - yarn format:check
      - yarn lint
      - yarn test
      - yarn test:integration:ci
